[package]
name = "ml"
version.workspace = true
edition.workspace = true

[features]
default = []
cuda = ["tch"]

[dependencies]
rayon = { workspace = true }
common = { path = "../common" }
indicators = { path = "../indicators" }
tch = { version = "0.16", optional = true }
ndarray.workspace = true
smartcore.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
chrono.workspace = true
