[package]
name = "strategies"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
db = { path = "../db" }
smc = { path = "../smc" }
indicators = { path = "../indicators" }
ml = { path = "../ml" }
serde.workspace = true
tracing.workspace = true
chrono.workspace = true

[dev-dependencies]
chrono.workspace = true
common = { path = "../common" }
indicators = { path = "../indicators" }
