[package]
name = "notifications"
version.workspace = true
edition.workspace = true

[dependencies]
db = { path = "../db" }
reqwest = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
