[package]
name = "data"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
db = { path = "../db" }
reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
futures-util = { workspace = true }
