[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
db = { path = "../db" }
data = { path = "../data" }
ml = { path = "../ml", features = ["cuda"] }
strategies = { path = "../strategies" }
risk = { path = "../risk" }
smc = { path = "../smc" }
indicators = { path = "../indicators" }
backtest = { path = "../backtest" }
actix-web.workspace = true
actix-cors.workspace = true
actix-ws.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
chrono.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
reqwest = { workspace = true }
sqlx = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["native-tls"] }
futures-util = { workspace = true }
async-trait.workspace = true
futures = "0.3.32"
rayon.workspace = true
base64 = "0.22.1"
