//! Configuration des routes HTTP — séparé de main.rs pour lisibilité.
use actix_web::web;
pub fn configurer(cfg: &mut web::ServiceConfig) {
    cfg.route("/health", web::get().to(crate::handlers::health_check))
        .service(
            web::resource("/api/assets/params")
                .route(web::get().to(crate::asset_params_handlers::get_asset_params))
                .route(web::put().to(crate::asset_params_handlers::put_asset_params)),
        )
        .route(
            "/api/assets",
            web::get().to(crate::assets_handlers::lister_assets),
        )
        .route(
            "/api/assets",
            web::post().to(crate::assets_handlers::ajouter_asset),
        )
        .route(
            "/api/assets/{id}",
            web::delete().to(crate::assets_handlers::supprimer_asset),
        )
        .route("/api/prix", web::get().to(crate::prix_handlers::get_prix))
        .route(
            "/api/prix/stream",
            web::get().to(crate::prix_stream::stream_prix),
        )
        .route("/api/candles", web::get().to(crate::handlers::get_candles))
        .route(
            "/api/strategies",
            web::get().to(crate::registre_strategies::lister_strategies),
        )
        .route(
            "/api/strategies/{id}",
            web::put().to(crate::registre_strategies::maj_strategie),
        )
        .route(
            "/api/strategies/{id}/performance",
            web::get().to(crate::registre_strategies::performance_strategie),
        )
        .route(
            "/api/strategies/{id}/capital",
            web::get().to(crate::capital_simule::capital_strategie),
        )
        .route(
            "/api/smc/rejeu",
            web::get().to(crate::smc_rejeu::get_rejeu),
        )
        .route(
            "/api/straddle/rejeu",
            web::get().to(crate::straddle_rejeu::get_rejeu),
        )
        .route(
            "/api/straddle/agenda",
            web::get().to(crate::straddle_agenda::get_agenda),
        )
        .route(
            "/api/rockets/candidats",
            web::get().to(crate::rockets_verticale::get_candidats),
        )
        .route(
            "/api/rockets/positions/cloturer",
            web::post().to(crate::rockets_cloture::cloturer_manuel),
        )
        .route(
            "/api/rockets/unlocks",
            web::get().to(crate::rockets_unlocks::lister),
        )
        .route(
            "/api/rockets/unlocks",
            web::post().to(crate::rockets_unlocks::ajouter),
        )
        .route(
            "/api/rockets/unlocks/{symbole}/{date}",
            web::delete().to(crate::rockets_unlocks::retirer),
        )
        .service(
            web::resource("/api/rockets/params")
                .route(web::get().to(crate::rockets_handlers::get_params))
                .route(web::put().to(crate::rockets_verticale::maj_params)),
        )
        .route(
            "/api/setups-formation",
            web::get().to(crate::setups_formation::get_setups),
        )
        .route(
            "/api/mt5/symboles",
            web::get().to(crate::mt5_collecteur::get_symboles),
        )
        .route(
            "/api/mt5/kline",
            web::post().to(crate::mt5_collecteur::post_kline),
        )
        .route(
            "/api/mt5/heartbeat",
            web::post().to(crate::mt5_collecteur::post_heartbeat),
        )
        .route(
            "/api/mt5/statut",
            web::get().to(crate::mt5_collecteur::get_statut),
        )
        .route(
            "/api/mt5/historique",
            web::post().to(crate::mt5_collecteur::post_historique),
        )
        .route(
            "/api/mt5/historique/etat",
            web::get().to(crate::mt5_etat_historique::get_etat),
        )
        .route(
            "/api/signaux",
            web::get().to(crate::signaux_handlers::get_signaux),
        )
        .route(
            "/api/signaux/mfe",
            web::post().to(crate::signaux_handlers::post_mfe_signaux),
        )
        .route(
            "/api/signaux/lots",
            web::post().to(crate::signaux_handlers::post_lots_signaux),
        )
        // Étape A2 Rockets actions — backfill Tiingo (lot manuel « Rattraper
        // maintenant » + état du compteur univers). Les ex-endpoints
        // d'import/scan/prescreen/contexte/news ont été supprimés le 05/09
        // (décision §7-3a : les boucles backend font déjà le travail ;
        // l'import NASDAQ Trader repose sur l'univers en base — réimport à
        // recâbler depuis git si besoin un jour).
        .route(
            "/api/rockets/actions/backfill",
            web::post().to(crate::rockets_actions_backfill::post_backfill),
        )
        .route(
            "/api/rockets/actions/backfill/etat",
            web::get().to(crate::rockets_actions_backfill::etat_backfill),
        )
        .route(
            "/api/straddle/creneaux-ia",
            web::get().to(crate::creneaux_ia::lister),
        )
        .route(
            "/api/straddle/creneaux-ia/calculer",
            web::post().to(crate::creneaux_ia::calculer_et_evaluer),
        )
        .route(
            "/api/straddle/creneaux-ia/armer",
            web::post().to(crate::creneaux_ia::armer),
        )
        .route(
            "/api/straddle/creneaux-ia/armer-file",
            web::post().to(crate::creneaux_ia::armer_file),
        )
        .route(
            "/api/straddle/creneaux-ia/ignorer",
            web::post().to(crate::creneaux_ia::ignorer),
        )
        .route(
            "/api/straddle/creneaux-ia/seuils",
            web::put().to(crate::creneaux_ia::mettre_seuils),
        )
        .route(
            "/api/smc/analyse",
            web::get().to(crate::smc_handlers::analyse_smc),
        )
        .route(
            "/api/smc/v12/analyse",
            web::get().to(crate::smc_v12_handlers::analyse_v12),
        )
        .route(
            "/api/indicators",
            web::get().to(crate::indicators_handlers::get_indicators),
        )
        .route(
            "/api/tendance/multi-tf",
            web::get().to(crate::tendance_handlers::tendance_multi_tf),
        )
        .route(
            "/api/ia/analyse",
            web::post().to(crate::ollama_handlers::analyser),
        )
        .route(
            "/api/ia/status",
            web::get().to(crate::ollama_handlers::statut),
        )
        .route(
            "/api/ia/signal/straddle",
            web::post().to(crate::straddle_signal_handler::generer_signal_straddle),
        )
        .route(
            "/api/straddle/analyser",
            web::post().to(crate::straddle_handlers::analyser),
        )
        .route(
            "/api/straddle/analyste",
            web::get().to(crate::straddle_analyste::consulter),
        )
        .route(
            "/api/straddle/analyste/rafraichir",
            web::post().to(crate::straddle_analyste::rafraichir),
        )
        .route(
            "/api/straddle/precision-horaire",
            web::post().to(crate::straddle_precision_handler::handler_precision_horaire),
        )
        .service(
            web::resource("/api/straddle/params")
                .route(web::get().to(crate::strategies_params_handlers::get_straddle_params))
                .route(web::put().to(crate::strategies_params_handlers::put_straddle_params)),
        )
        .route(
            "/api/straddle/monitoring-ml",
            web::get().to(crate::straddle_ml_handlers::monitoring_ml),
        )
        .route(
            "/api/straddle/calibration",
            web::get().to(crate::straddle_ml_handlers::get_calibration),
        )
        .route(
            "/api/smc/monitoring-ml",
            web::get().to(crate::smc_monitoring_handlers::monitoring_ml),
        )
        .route(
            "/api/smc/calibration",
            web::get().to(crate::smc_monitoring_handlers::get_calibration),
        )
        .route(
            "/api/config",
            web::get().to(crate::config_handlers::get_config),
        )
        .route(
            "/api/config",
            web::post().to(crate::config_handlers::post_config),
        )
        .route(
            "/api/calendar",
            web::get().to(crate::calendar_handlers::get_calendar),
        )
        .route(
            "/api/sentiment/marche",
            web::get().to(crate::sentiment_handlers::get_sentiment_marche),
        )
        .route(
            "/api/sentiment/composite",
            web::get().to(crate::sentiment_composite::get_sentiment_composite),
        )
        .route(
            "/api/news/traduire",
            web::get().to(crate::news_handlers::get_traduire),
        )
        // ── Centre d'analyse « Rapport d'activité » (phases 1-3, 04/09) ────
        .route(
            "/api/analyses",
            web::get().to(crate::analyses::get_analyses),
        )
        .route(
            "/api/analyses/{strategie}",
            web::get().to(crate::analyses::get_analyse),
        )
        .route(
            "/api/analyses/{strategie}/ia",
            web::post().to(crate::analyses_ia::post_analyse_ia),
        )
        .route(
            "/api/analyses/{strategie}/historique",
            web::get().to(crate::analyses::get_historique_analyses),
        )
        // ── Journal de bord du propriétaire (§16 — notes par trade) ──────────
        .route(
            "/api/journal/comptes",
            web::get().to(crate::journal_bord::get_comptes),
        )
        .route(
            "/api/journal/{signal_id}",
            web::get().to(crate::journal_bord::get_journal),
        )
        .route(
            "/api/journal/{signal_id}",
            web::post().to(crate::journal_bord::post_note),
        )
        .route(
            "/api/journal/entree/{id}",
            web::delete().to(crate::journal_bord::supprimer_note),
        )
        // ── Armement SMC par couple (outil Paramètres › SMC — 04/09) ─────────
        .route(
            "/api/smc/couples",
            web::get().to(crate::reglages_smc::get_couples),
        )
        .route(
            "/api/smc/couples",
            web::put().to(crate::reglages_smc::put_couples),
        )
        .route(
            "/api/stream",
            web::get().to(crate::ws_handlers::stream_market),
        )
        .route(
            "/api/data/coverage",
            web::get().to(crate::data_handlers::get_coverage),
        )
        .service(
            web::resource("/api/worker/config")
                .route(web::get().to(crate::worker_handlers::get_worker_config))
                .route(web::put().to(crate::worker_handlers::put_worker_config)),
        )
        .route(
            "/api/worker/status",
            web::get().to(crate::worker_handlers::get_worker_status),
        )
        // ── Runtime tick (Phase 1 ROADMAP — Gate 1 : concordance bougies) ──
        .route(
            "/api/runtime/concordance",
            web::get().to(crate::runtime_handlers::get_concordance),
        )
        // ── Replay harness v12 (Phase 2.5 — Gate 2, méthode R) ──────────────
        .route(
            "/api/runtime/replay",
            web::post().to(crate::runtime_handlers::post_replay),
        )
        .route(
            "/api/runtime/replay",
            web::get().to(crate::runtime_handlers::get_replays),
        )
        .route(
            "/api/runtime/replay/{id}",
            web::get().to(crate::runtime_handlers::get_replay_journal),
        )
        // ── Émissions live du runtime (shadow mode 2.6 — Gate 2) ────────────
        .route(
            "/api/runtime/emissions",
            web::get().to(crate::runtime_handlers::get_emissions),
        )
        // ── Revue de presse (Phase 4.1) ────────────────────────────────────────
        .route(
            "/api/presse/articles",
            web::get().to(crate::presse_handlers::get_articles),
        )
        .route(
            "/api/presse/articles/{hash}/ouvrir",
            web::post().to(crate::presse_handlers::ouvrir_article),
        )
        .route(
            "/api/presse/sources",
            web::get().to(crate::presse_handlers::get_sources),
        )
        .route(
            "/api/presse/sources",
            web::post().to(crate::presse_handlers::post_source),
        )
        .route(
            "/api/presse/sources/{id}",
            web::delete().to(crate::presse_handlers::delete_source),
        )
        .route(
            "/api/presse/brief",
            web::post().to(crate::presse_handlers::post_brief),
        )
        .route(
            "/api/presse/briefs",
            web::get().to(crate::presse_handlers::get_briefs),
        )
        .route(
            "/api/alertes-prix",
            web::get().to(crate::alertes_prix::lister),
        )
        .route(
            "/api/alertes-prix",
            web::post().to(crate::alertes_prix::creer),
        )
        .route(
            "/api/alertes-prix/{id}",
            web::delete().to(crate::alertes_prix::supprimer),
        )
        .route(
            "/api/creneaux-volatilite",
            web::get().to(crate::creneaux_job::lister),
        )
        .route(
            "/api/volatility/patterns",
            web::get().to(crate::volatility_handlers::get_patterns),
        )
        .route(
            "/api/volatility/patterns-jour",
            web::get().to(crate::volatility_handlers::get_patterns_jour),
        )
        .route(
            "/api/prompts",
            web::get().to(crate::prompts_handler::lister_prompts),
        )
        .service(
            web::resource("/api/prompts/{id}")
                .route(web::put().to(crate::prompts_handler::modifier_prompt))
                .route(web::delete().to(crate::prompts_handler::restaurer_prompt)),
        );
    crate::routes_ml::configurer(cfg);
    crate::routes_rockets::configurer(cfg);
}
