//! Configuration des routes HTTP — séparé de main.rs pour lisibilité.
use actix_web::web;
pub fn configurer(cfg: &mut web::ServiceConfig) {
    cfg.route("/health", web::get().to(crate::handlers::health_check))
        .service(
            web::resource("/api/assets/params")
                .route(web::get().to(crate::asset_params_handlers::get_asset_params))
                .route(web::put().to(crate::asset_params_handlers::put_asset_params)),
        )
        .route(
            "/api/assets",
            web::get().to(crate::assets_handlers::lister_assets),
        )
        .route(
            "/api/assets",
            web::post().to(crate::assets_handlers::ajouter_asset),
        )
        .route(
            "/api/assets/{id}",
            web::delete().to(crate::assets_handlers::supprimer_asset),
        )
        .route(
            "/api/assets/{id}/ml",
            web::patch().to(crate::assets_handlers::set_ml_actif),
        )
        .route("/api/prix", web::get().to(crate::prix_handlers::get_prix))
        .route(
            "/api/prix/stream",
            web::get().to(crate::prix_stream::stream_prix),
        )
        .route("/api/candles", web::get().to(crate::handlers::get_candles))
        .route(
            "/api/strategies",
            web::get().to(crate::registre_strategies::lister_strategies),
        )
        .route(
            "/api/strategies/{id}",
            web::put().to(crate::registre_strategies::maj_strategie),
        )
        .route(
            "/api/strategies/{id}/performance",
            web::get().to(crate::registre_strategies::performance_strategie),
        )
        .route(
            "/api/straddle/agenda",
            web::get().to(crate::straddle_agenda::get_agenda),
        )
        .route(
            "/api/rockets/candidats",
            web::get().to(crate::rockets_verticale::get_candidats),
        )
        .route(
            "/api/rockets/params",
            web::put().to(crate::rockets_verticale::maj_params),
        )
        .route(
            "/api/setups-formation",
            web::get().to(crate::setups_formation::get_setups),
        )
        .route(
            "/api/mt5/symboles",
            web::get().to(crate::mt5_collecteur::get_symboles),
        )
        .route(
            "/api/mt5/kline",
            web::post().to(crate::mt5_collecteur::post_kline),
        )
        .route(
            "/api/mt5/heartbeat",
            web::post().to(crate::mt5_collecteur::post_heartbeat),
        )
        .route(
            "/api/mt5/statut",
            web::get().to(crate::mt5_collecteur::get_statut),
        )
        .route(
            "/api/mt5/historique",
            web::post().to(crate::mt5_collecteur::post_historique),
        )
        .route(
            "/api/mt5/historique/etat",
            web::get().to(crate::mt5_etat_historique::get_etat),
        )
        .route(
            "/api/signaux",
            web::get().to(crate::signaux_handlers::get_signaux),
        )
        .route(
            "/api/signaux/mfe",
            web::post().to(crate::signaux_handlers::post_mfe_signaux),
        )
        // Étape A Rockets actions — univers NASDAQ Trader + clé Tiingo
        .route(
            "/api/rockets/actions/univers/charger",
            web::post().to(crate::rockets_actions::charger_univers),
        )
        .route(
            "/api/rockets/actions/univers",
            web::get().to(crate::rockets_actions::lire_univers),
        )
        .route(
            "/api/rockets/actions/contexte",
            web::get().to(crate::rockets_actions::lire_contexte),
        )
        .route(
            "/api/rockets/actions/scan",
            web::post().to(crate::rockets_actions_scanner::post_scan),
        )
        .route(
            "/api/rockets/actions/prescreen",
            web::get().to(crate::rockets_actions_scanner::get_prescreen),
        )
        .route(
            "/api/rockets/actions/news/collecter",
            web::post().to(crate::rockets_actions_news::post_collecter),
        )
        .route(
            "/api/rockets/actions/backfill",
            web::post().to(crate::rockets_actions_backfill::post_backfill),
        )
        .route(
            "/api/rockets/actions/backfill/etat",
            web::get().to(crate::rockets_actions_backfill::etat_backfill),
        )
        .route(
            "/api/smc/analyse",
            web::get().to(crate::smc_handlers::analyse_smc),
        )
        .route(
            "/api/smc/v12/analyse",
            web::get().to(crate::smc_v12_handlers::analyse_v12),
        )
        .route(
            "/api/indicators",
            web::get().to(crate::indicators_handlers::get_indicators),
        )
        .route(
            "/api/tendance/multi-tf",
            web::get().to(crate::tendance_handlers::tendance_multi_tf),
        )
        .route(
            "/api/ia/analyse",
            web::post().to(crate::ollama_handlers::analyser),
        )
        .route("/api/ia/chat", web::post().to(crate::ollama_handlers::chat))
        .route(
            "/api/ia/diagram",
            web::post().to(crate::ollama_handlers::generer_diagram),
        )
        .route(
            "/api/ia/chart",
            web::post().to(crate::ollama_handlers::analyser_chart),
        )
        .route(
            "/api/ia/status",
            web::get().to(crate::ollama_handlers::statut),
        )
        .route(
            "/api/ia/signal/straddle",
            web::post().to(crate::straddle_signal_handler::generer_signal_straddle),
        )
        .route(
            "/api/straddle/analyser",
            web::post().to(crate::straddle_handlers::analyser),
        )
        .route(
            "/api/straddle/precision-horaire",
            web::post().to(crate::straddle_precision_handler::handler_precision_horaire),
        )
        .service(
            web::resource("/api/straddle/params")
                .route(web::get().to(crate::strategies_params_handlers::get_straddle_params))
                .route(web::put().to(crate::strategies_params_handlers::put_straddle_params)),
        )
        .route(
            "/api/straddle/monitoring-ml",
            web::get().to(crate::straddle_ml_handlers::monitoring_ml),
        )
        .route(
            "/api/straddle/calibration",
            web::get().to(crate::straddle_ml_handlers::get_calibration),
        )
        .service(
            web::resource("/api/smc/params")
                .route(web::get().to(crate::strategies_params_handlers::get_smc_params))
                .route(web::put().to(crate::strategies_params_handlers::put_smc_params)),
        )
        .route(
            "/api/smc/monitoring-ml",
            web::get().to(crate::smc_monitoring_handlers::monitoring_ml),
        )
        .route(
            "/api/smc/calibration",
            web::get().to(crate::smc_monitoring_handlers::get_calibration),
        )
        .route(
            "/api/config",
            web::get().to(crate::config_handlers::get_config),
        )
        .route(
            "/api/config",
            web::post().to(crate::config_handlers::post_config),
        )
        .route(
            "/api/calendar",
            web::get().to(crate::calendar_handlers::get_calendar),
        )
        .route(
            "/api/sentiment/marche",
            web::get().to(crate::sentiment_handlers::get_sentiment_marche),
        )
        .route(
            "/api/sentiment/composite",
            web::get().to(crate::sentiment_composite::get_sentiment_composite),
        )
        .route(
            "/api/news/alertes",
            web::get().to(crate::news_handlers::get_news_alertes),
        )
        .route(
            "/api/news/traduire",
            web::get().to(crate::news_handlers::get_traduire),
        )
        .route(
            "/api/stream",
            web::get().to(crate::ws_handlers::stream_market),
        )
        .route(
            "/api/data/coverage",
            web::get().to(crate::data_handlers::get_coverage),
        )
        .service(
            web::resource("/api/worker/config")
                .route(web::get().to(crate::worker_handlers::get_worker_config))
                .route(web::put().to(crate::worker_handlers::put_worker_config)),
        )
        .route(
            "/api/worker/status",
            web::get().to(crate::worker_handlers::get_worker_status),
        )
        // ── Runtime tick (Phase 1 ROADMAP — Gate 1 : concordance bougies) ──
        .route(
            "/api/runtime/concordance",
            web::get().to(crate::runtime_handlers::get_concordance),
        )
        // ── Replay harness v12 (Phase 2.5 — Gate 2, méthode R) ──────────────
        .route(
            "/api/runtime/replay",
            web::post().to(crate::runtime_handlers::post_replay),
        )
        .route(
            "/api/runtime/replay",
            web::get().to(crate::runtime_handlers::get_replays),
        )
        .route(
            "/api/runtime/replay/{id}",
            web::get().to(crate::runtime_handlers::get_replay_journal),
        )
        // ── Émissions live du runtime (shadow mode 2.6 — Gate 2) ────────────
        .route(
            "/api/runtime/emissions",
            web::get().to(crate::runtime_handlers::get_emissions),
        )
        // ── Revue de presse (Phase 4.1) ────────────────────────────────────────
        .route(
            "/api/presse/articles",
            web::get().to(crate::presse_handlers::get_articles),
        )
        .route(
            "/api/presse/articles/{hash}/ouvrir",
            web::post().to(crate::presse_handlers::ouvrir_article),
        )
        .route(
            "/api/presse/sources",
            web::get().to(crate::presse_handlers::get_sources),
        )
        .route(
            "/api/presse/sources",
            web::post().to(crate::presse_handlers::post_source),
        )
        .route(
            "/api/presse/sources/{id}",
            web::delete().to(crate::presse_handlers::delete_source),
        )
        .route(
            "/api/presse/brief",
            web::post().to(crate::presse_handlers::post_brief),
        )
        .route(
            "/api/presse/briefs",
            web::get().to(crate::presse_handlers::get_briefs),
        )
        .route(
            "/api/presse/briefs/{id}",
            web::get().to(crate::presse_handlers::get_brief),
        )
        .route(
            "/api/alertes-prix",
            web::get().to(crate::alertes_prix::lister),
        )
        .route(
            "/api/alertes-prix",
            web::post().to(crate::alertes_prix::creer),
        )
        .route(
            "/api/alertes-prix/{id}",
            web::delete().to(crate::alertes_prix::supprimer),
        )
        .route(
            "/api/creneaux-volatilite",
            web::get().to(crate::creneaux_job::lister),
        )
        .route(
            "/api/volatility/patterns",
            web::get().to(crate::volatility_handlers::get_patterns),
        )
        .route(
            "/api/volatility/patterns-jour",
            web::get().to(crate::volatility_handlers::get_patterns_jour),
        )
        .route(
            "/api/prompts",
            web::get().to(crate::prompts_handler::lister_prompts),
        )
        .service(
            web::resource("/api/prompts/{id}")
                .route(web::put().to(crate::prompts_handler::modifier_prompt))
                .route(web::delete().to(crate::prompts_handler::restaurer_prompt)),
        );
    crate::routes_ml::configurer(cfg);
    crate::routes_rockets::configurer(cfg);
}
