//! Configuration des routes HTTP — séparé de main.rs pour lisibilité.
use actix_web::web;

pub fn configurer(cfg: &mut web::ServiceConfig) {
    cfg.route("/health", web::get().to(crate::handlers::health_check))
        .route(
            "/api/assets/params",
            web::get().to(crate::asset_params_handlers::get_asset_params),
        )
        .route(
            "/api/assets/params",
            web::put().to(crate::asset_params_handlers::put_asset_params),
        )
        .route(
            "/api/assets",
            web::get().to(crate::assets_handlers::lister_assets),
        )
        .route(
            "/api/assets",
            web::post().to(crate::assets_handlers::ajouter_asset),
        )
        .route(
            "/api/assets/{id}",
            web::delete().to(crate::assets_handlers::supprimer_asset),
        )
        .route(
            "/api/assets/{id}/ml",
            web::patch().to(crate::assets_handlers::set_ml_actif),
        )
        .route("/api/prix", web::get().to(crate::prix_handlers::get_prix))
        .route(
            "/api/prix/stream",
            web::get().to(crate::prix_stream::stream_prix),
        )
        .route(
            "/api/marche/klines",
            web::get().to(crate::prix_handlers::get_klines_crypto),
        )
        .route("/api/candles", web::get().to(crate::handlers::get_candles))
        .route(
            "/api/prix-actuel",
            web::get().to(crate::handlers::get_prix_actuel),
        )
        .route(
            "/api/signaux",
            web::get().to(crate::signaux_handlers::get_signaux),
        )
        .route(
            "/api/signaux/export",
            web::post().to(crate::export_handlers::exporter_signaux_csv),
        )
        .route(
            "/api/smc/analyse",
            web::get().to(crate::smc_handlers::analyse_smc),
        )
        .service(
            web::resource("/api/smc/score-debug")
                .route(web::get().to(crate::smc_handlers::score_debug)),
        )
        .route(
            "/api/indicators",
            web::get().to(crate::indicators_handlers::get_indicators),
        )
        .route(
            "/api/tendance/multi-tf",
            web::get().to(crate::tendance_handlers::tendance_multi_tf),
        )
        .route(
            "/api/ia/analyse",
            web::post().to(crate::ollama_handlers::analyser),
        )
        .route("/api/ia/chat", web::post().to(crate::ollama_handlers::chat))
        .route(
            "/api/ia/diagram",
            web::post().to(crate::ollama_handlers::generer_diagram),
        )
        .route(
            "/api/ia/chart",
            web::post().to(crate::ollama_handlers::analyser_chart),
        )
        .route(
            "/api/ia/chart/local",
            web::post().to(crate::ollama_handlers::analyser_chart_local),
        )
        .route(
            "/api/ia/status",
            web::get().to(crate::ollama_handlers::statut),
        )
        .route(
            "/api/ia/signal",
            web::post().to(crate::ollama_handlers::generer_signal),
        )
        .route(
            "/api/ia/ajustements",
            web::post().to(crate::ollama_ajustements_handler::ajustements),
        )
        .route(
            "/api/ia/signal/straddle",
            web::post().to(crate::straddle_signal_handler::generer_signal_straddle),
        )
        .route(
            "/api/straddle/analyser",
            web::post().to(crate::straddle_handlers::analyser),
        )
        .route(
            "/api/straddle/creneaux",
            web::get().to(crate::straddle_handlers::lister_creneaux),
        )
        .route(
            "/api/straddle/creneaux/{id}",
            web::patch().to(crate::straddle_handlers::mettre_a_jour_creneau),
        )
        .route(
            "/api/straddle/creneaux/{id}/precision",
            web::post().to(crate::straddle_handlers::handler_analyser_precision),
        )
        .route(
            "/api/straddle/precision-horaire",
            web::post().to(crate::straddle_precision_handler::handler_precision_horaire),
        )
        .route(
            "/api/straddle/params",
            web::get().to(crate::strategies_params_handlers::get_straddle_params),
        )
        .route(
            "/api/straddle/params",
            web::put().to(crate::strategies_params_handlers::put_straddle_params),
        )
        .route(
            "/api/straddle/volatilite-live",
            web::get().to(crate::straddle_ml_handlers::volatilite_live),
        )
        .route(
            "/api/straddle/monitoring-ml",
            web::get().to(crate::straddle_ml_handlers::monitoring_ml),
        )
        .route(
            "/api/straddle/calibration",
            web::get().to(crate::straddle_ml_handlers::get_calibration),
        )
        .route(
            "/api/straddle/pics",
            web::get().to(crate::straddle_ml_handlers::get_pics),
        )
        .route(
            "/api/straddle/feedback",
            web::get().to(crate::straddle_ml_handlers::get_feedback),
        )
        .route(
            "/api/straddle/feedback/{signal_id}/cloturer",
            web::post().to(crate::straddle_ml_handlers::cloturer_feedback),
        )
        .route(
            "/api/straddle/equity",
            web::get().to(crate::straddle_ml_handlers::get_equity),
        )
        .route("/api/straddle/dev/seed-creneaux", web::post().to(crate::straddle_ml_handlers::dev_seed_creneaux))
        .route("/api/straddle/dev/signal-test", web::post().to(crate::straddle_ml_handlers::dev_signal_test))
        .route(
            "/api/smc/params",
            web::get().to(crate::strategies_params_handlers::get_smc_params),
        )
        .route(
            "/api/smc/params",
            web::put().to(crate::strategies_params_handlers::put_smc_params),
        )
        .route(
            "/api/smc/monitoring-ml",
            web::get().to(crate::smc_monitoring_handlers::monitoring_ml),
        )
        .route(
            "/api/smc/calibration",
            web::get().to(crate::smc_monitoring_handlers::get_calibration),
        )
        .route(
            "/api/smc/feedback",
            web::get().to(crate::smc_monitoring_handlers::get_feedback),
        )
        .route(
            "/api/smc/equity",
            web::get().to(crate::smc_monitoring_handlers::get_equity),
        )
        .route(
            "/api/smc/baremes",
            web::get().to(crate::smc_monitoring_handlers::get_baremes),
        )
        .route(
            "/api/straddle/seuils-effectifs",
            web::get().to(crate::straddle_ml_handlers::get_seuils_effectifs),
        )
        .route(
            "/api/rockets/seuils-effectifs",
            web::get().to(crate::rockets_ml_handlers::get_seuils_effectifs),
        )
        .route(
            "/api/config",
            web::get().to(crate::config_handlers::get_config),
        )
        .route(
            "/api/config",
            web::post().to(crate::config_handlers::post_config),
        )
        .route("/api/ig/status", web::get().to(crate::ig_handlers::ig_status))
        .route(
            "/api/ig/statut-local",
            web::get().to(crate::ig_handlers::ig_statut_local),
        )
        .route(
            "/api/ig/search",
            web::get().to(crate::ig_handlers::ig_search_markets),
        )
        .route(
            "/api/calendar",
            web::get().to(crate::calendar_handlers::get_calendar),
        )
        .route(
            "/api/sentiment/marche",
            web::get().to(crate::sentiment_handlers::get_sentiment_marche),
        )
        .route(
            "/api/news/alertes",
            web::get().to(crate::news_handlers::get_news_alertes),
        )
        .route(
            "/api/news/contenu",
            web::get().to(crate::news_handlers::get_contenu_article),
        )
        .route(
            "/api/news/traduire",
            web::get().to(crate::news_handlers::get_traduire),
        )
        .route(
            "/api/news/fear-greed",
            web::get().to(crate::news_fear_greed::get_fear_greed),
        )
        .route(
            "/api/news/lu",
            web::post().to(crate::news_lus_handlers::marquer_lu),
        )
        .route(
            "/api/news/lus",
            web::get().to(crate::news_lus_handlers::lire_lus),
        )
        .route(
            "/api/news/contexte-marche",
            web::get().to(crate::news_context_handler::get_contexte_marche),
        )
        .route(
            "/api/stream",
            web::get().to(crate::ws_handlers::stream_market),
        )
        .route(
            "/api/signal-engine/start",
            web::post().to(crate::engine_handlers::demarrer_engine),
        )
        .route(
            "/api/signal-engine/stop",
            web::post().to(crate::engine_handlers::arreter_engine),
        )
        .route(
            "/api/signal-engine/status",
            web::get().to(crate::engine_handlers::statut_engine),
        )
        .route(
            "/api/signal-engine/stream",
            web::get().to(crate::engine_handlers::stream_signaux),
        )
        .route(
            "/api/data/coverage",
            web::get().to(crate::data_handlers::get_coverage),
        )
        .route(
            "/api/data/collect",
            web::post().to(crate::data_handlers::post_collect),
        )
        .route(
            "/api/data/import-mt5",
            web::post().to(crate::data_mt5_handlers::post_import_mt5),
        )
        .service(
            web::resource("/api/smc/analyse-llm")
                .route(web::get().to(crate::smc_analyse_handler::get_derniere_analyse))
                .route(web::post().to(crate::smc_analyse_handler::lancer_analyse)),
        )
        .route(
            "/api/volatility/patterns",
            web::get().to(crate::volatility_handlers::get_patterns),
        )
        .route(
            "/api/ia/ab-test",
            web::get().to(crate::ab_test_handlers::get_ab_test),
        )
        .route(
            "/api/prompts",
            web::get().to(crate::prompts_handler::lister_prompts),
        )
        .service(
            web::resource("/api/prompts/{id}")
                .route(web::put().to(crate::prompts_handler::modifier_prompt))
                .route(web::delete().to(crate::prompts_handler::restaurer_prompt)),
        );
    crate::routes_ml::configurer(cfg);
    crate::routes_rockets::configurer(cfg);
}
